import os
import sys
import datetime as date
import time
import solution

IN_EXT = ".txt"
OUT_EXT = ".txt"
FILE_NAMES = {
    "a": "a",
    "b": "b",
    "c": "c",
    "d": "d",
    "e": "e",
    "f": "f",
    "t": "test"
}


def main():
    args = [a for a in sys.argv[1::]]
    # at least 1 arguments has to be passed
    assert len(args) > 0, "No argument specified"

    cwd = os.path.abspath(__file__).replace(__file__, "")

    # input path is generated by the recorded name of the file in FILE_NAMES
    # and the extension stored in IN_EXT if a single letter is passed as argument
    # otherwise the whole argument is taken as relative or full path
    in_path = args[0] if len(args[0]) > 1 else \
        f"{cwd}input/{FILE_NAMES[args[0].lower()]}{IN_EXT}"
    assert os.path.exists(in_path), "File not found" 

    # output path is generated by the input path replacing "input" with "output"
    # and the extension with OUT_EXT. Also the date and time is appended
    # to ensure results are not overwritten between runs.
    # Output folder should exist before launching the script
    assert os.path.exists(f"{cwd}output"), "No output folder found"
    out_path = in_path.replace("input", "output")[:-len(IN_EXT)]
    out_path = out_path + "-" + date.datetime.now().strftime("%y%m%d-%H%M%S") + OUT_EXT

    print("RUNNING...")
    start_time = time.perf_counter()
    
    # a list of lines is generated from the input file
    with open(in_path, "r") as inputFile:
        lines = [x.strip() for x in inputFile.readlines()]

    # the list of lines is passed to the main algorithm
    # which returns a new list of lines as result
    out_lines = solution.compute(lines)

    # the output lines are written to the output file
    with open(out_path, "w") as outputFile:
        outputFile.write("\n".join(out_lines))

    elapsed_time = time.perf_counter() - start_time
    print(f"COMPLETED IN {elapsed_time:0.4f}s")

if __name__ == "__main__":
    main()